language: node_js
node_js:
  - 6.9.1

branches:
  only:
    - master

env:
  global:
    - CXX=g++-4.8
    - GITHUB_ORG="https://GH_TOKEN@github.com/book-monkey2-build"
    - GITHUB_NAME="The Buildbot"
    - GITHUB_EMAIL="buildbot@angular2buch.de"
    - NAME=book-monkey-rdx

cache:
  directories:
    - node_modules

install:
  - npm i --silent -g @angular/cli@1.0.0
  - npm i --silent -g angular-cli-ghpages

script:
  - npm i --silent
  - ng build --prod --progress=false
  - echo "$NAME.angular-buch.com" > dist/CNAME
  - cp dist/index.html dist/404.html
  - ngh --repo="$GITHUB_ORG/$NAME.git" --name="$GITHUB_NAME" --email="$GITHUB_EMAIL"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

# a build will finish as soon as a job has failed
matrix:
  fast_finish: true
